# Generated by Django 5.0.7 on 2024-09-27 00:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='last_reset',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
