# Generated by Django 5.0.7 on 2024-09-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_portfolio_balance_alter_portfolio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliostock',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
