# Generated by Django 5.0.7 on 2024-10-13 05:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_portfoliohistory_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='available_gains',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
