# Generated by Django 5.1.1 on 2024-09-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0002_persistentportfolio_persistentportfoliostock'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazaarlisting',
            name='industry',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bazaarlisting',
            name='name',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bazaarlisting',
            name='symbol',
            field=models.CharField(default='N/A', max_length=10),
            preserve_default=False,
        ),
    ]
