# Generated by Django 5.1.1 on 2024-09-30 06:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0003_bazaarlisting_industry_bazaarlisting_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bazaarlisting',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='bazaarlisting',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bazaarlisting',
            name='symbol',
        ),
        migrations.AddField(
            model_name='bazaarlisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
