# Generated by Django 5.1.1 on 2024-09-30 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0004_remove_bazaarlisting_industry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bazaarlisting',
            name='created_at',
        ),
        migrations.AddField(
            model_name='bazaarlisting',
            name='name',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bazaarlisting',
            name='symbol',
            field=models.CharField(default='N/A', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bazaarlisting',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bazaar.inventorystock'),
        ),
    ]
