# Generated by Django 5.1.1 on 2024-09-30 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0005_remove_bazaarlisting_created_at_bazaarlisting_name_and_more'),
        ('stocks', '0007_portfoliohistory_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazaarlisting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bazaarlisting',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stocks.stock'),
        ),
    ]
