# Generated by Django 5.1.1 on 2024-10-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0007_alter_bazaarlisting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazaaruserprofile',
            name='inventory_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='bazaaruserprofile',
            name='market_listing_limit',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='bazaaruserprofile',
            name='persistent_portfolio_limit',
            field=models.IntegerField(default=6),
        ),
    ]
