# Generated by Django 5.0.7 on 2024-10-13 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0008_bazaaruserprofile_inventory_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(choices=[('COMMISSION', 'Sell Value Multiplier'), ('TENACIOUS', 'Chance to Keep Shares'), ('SUBSIDIZED', 'Bonus Sell Value'), ('INSIDER', 'Chance to Buy Bonus Shares'), ('GLITCHED', 'Chance to Change into Random Stock when shares are bought or sold'), ('SHORTSQUEEZE', 'Inverse Gains when shares are sold')], max_length=20)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='persistentportfoliostock',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.persistentportfolio'),
        ),
        migrations.AddField(
            model_name='persistentportfoliostock',
            name='tags',
            field=models.ManyToManyField(to='bazaar.tag'),
        ),
    ]
