# Generated by Django 5.0.7 on 2024-10-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0009_tag_alter_persistentportfoliostock_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazaarlisting',
            name='tags',
            field=models.ManyToManyField(to='bazaar.tag'),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='tags',
            field=models.ManyToManyField(to='bazaar.tag'),
        ),
    ]
